## Assignment 04

In this notebook, you will implement

- data import, wrangling/cleanup with pandas
- dimensionality reduction
- clustering
- storing the pandas dataframe in an sqlite database

The file server.py does not have to be changed, it serves the data with an API using flask

You will then visualize the data in a frontend

### Step 1: Import Dataset From File

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_json.html

In [1]:
import pandas as pd
import sqlite3

In [2]:
iris = pd.read_json("iris.json")

In [3]:
# you can remove dtaa like this
iris = iris.drop("class", axis=1)

In [4]:
# look at first few rows
iris.head()

          name  sepallength  sepalwidth  petallength  petalwidth
0  Iris-setosa          5.1         3.5          1.4         0.2
1  Iris-setosa          4.9         3.0          1.4         0.2
2  Iris-setosa          4.7         3.2          1.3         0.2
3  Iris-setosa          4.6         3.1          1.5         0.2
4  Iris-setosa          5.0         3.6          1.4         0.2

In [5]:
# some statistics
iris.describe()

       sepallength  sepalwidth  petallength  petalwidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

### Step 2: Dimensionality Reduction

For older apporaches see https://scikit-learn.org/stable/index.html
For UMAP see https://github.com/lmcinnes/umap

In [6]:
# TODO: implement here

### Step 3: Clustering

See https://scikit-learn.org/stable/index.html

In [7]:
# TODO: implement here

### Step 4: Write Results to Database

Write the orginal data (the part you kept) along with the dimensionality recudction coordinates and the cluster IDs to the database


Open the database

https://docs.python.org/3.9/library/sqlite3.html (pay attention to your python version)

In [8]:
connection = sqlite3.connect("./data.db")

Write to database 

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sql.html#pandas.DataFrame.to_sql

In [9]:
iris.to_sql("iris", con=connection, if_exists='replace',
           index_label='id')

150

Close database connection

In [10]:
connection.close()